language: java
jdk:
  - oraclejdk8
env:
  global:
    - GRADLE_OPTS="-Xms128m"

sudo: required

services:
  - docker

script:  ./gradlew -Dtest.single=StateSynchronizerTest integrationtests:test

notifications:
  slack: emcnautilus:UZK3F72LSRYWXUuvlzSilFyy
  email:
    - arvind.kandhare@dell.com
    - tom.kaitchuck@dell.com
    - andrei.paduroiu@dell.com
    - shivesh.ranjan@dell.com
    - bhargav.gulavani@dell.com
    - sandeep.shridhar@dell.com
    - Vijayalakshmi.Veerubhotla@emc.com
    - Abhijeet.Jadhav@emc.com
    - Flavio.Junqueira@emc.com

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ccceafaf-7c60-4a02-9165-480174b535a2
