language: java
jdk:
  - oraclejdk8
env:
  global:
    - GRADLE_OPTS="-Xms128m"

sudo: required

services:
  - docker

script: ./gradlew check && ./gradlew distTar && ./gradlew pushPravegaHostImage && ./gradlew pushPravegaControllerImage

notifications:
  slack: emcnautilus:UZK3F72LSRYWXUuvlzSilFyy
  email:
    - arvind.kandhare@dell.com
    - tom.kaitchuck@dell.com
    - andrei.paduroiu@dell.com
    - shivesh.ranjan@dell.com
    - bhargav.gulavani@dell.com
    - sandeep.shridhar@dell.com
    - Vijayalakshmi.Veerubhotla@emc.com
    - Abhijeet.Jadhav@emc.com
    - Flavio.Junqueira@emc.com

