# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
---
- name: add ppa
  command: add-apt-repository ppa:openjdk-r/ppa -y
  sudo: yes

- name: apt update
  command: apt-get -y update
  sudo: yes

- name: Install java
  command: apt-get install -y openjdk-8-jdk
  sudo: yes

- name: Install unzip
  command: apt-get install -y unzip
  sudo: yes

- name: Copy pravega to remote node
  copy:
      src: data/pravega-0.1.0-SNAPSHOT.tgz
      dest: /

- name: Untar controller
  command: tar -xvf /pravega-0.1.0-SNAPSHOT.tgz

- name: Create pravega workdir
  shell: mkdir -p /opt/pravega
  sudo: yes

- name: Move pravega dist
  shell: mv /root/pravega-*/* /opt/pravega/
  sudo: yes
